# Generated by Django 4.2.6 on 2023-10-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('posted', 'Publicado')], default='draft'),
        ),
    ]
